[package]
name = "Devnet_baby_suiduckz_nft"
version = "0.0.1"
edition = "2024.beta"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/devnet" }

[addresses]
Devnet baby suiduckz nft = "0x0"
